# Site settings
title: x-Shen's Blog
email: shenx3@uci.edu
description: > # x-Shen's blog on github.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "x-shen.github.io" # the base hostname & protocol for your site
twitter_username: x-Shen
github_username:  x-Shen

# Build settings
markdown: kramdown
